# Generated by Django 4.2.2 on 2025-01-29 18:45

import datetime

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активная бронь"),
                ),
                ("date_reserved", models.DateField(verbose_name="Дата бронирования")),
                ("time_reserved", models.TimeField(verbose_name="Время бронирования")),
                (
                    "duration",
                    models.DurationField(
                        default=datetime.timedelta(seconds=7200),
                        verbose_name="Продолжительность",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название ресторана"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+7",
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=250, unique=True, verbose_name="Адрес"),
                ),
                ("description", models.TextField(verbose_name="Описание ресторана")),
                (
                    "history",
                    models.TextField(
                        blank=True, null=True, verbose_name="История ресторана"
                    ),
                ),
                (
                    "mission",
                    models.TextField(
                        blank=True, null=True, verbose_name="Миссия ресторана"
                    ),
                ),
                (
                    "command",
                    models.TextField(blank=True, null=True, verbose_name="Команда"),
                ),
                ("services", models.TextField(verbose_name="Предоставляемые услуги")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото ресторана",
                        null=True,
                        upload_to="restaurant/photo",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресторан",
                "verbose_name_plural": "Рестораны",
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Номер стола")),
                (
                    "seats",
                    models.PositiveIntegerField(verbose_name="Общее количество мест"),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="restaurants.restaurant",
                        verbose_name="Ресторан",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
            },
        ),
        migrations.CreateModel(
            name="ReserveHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(verbose_name="Время отмены бронирования"),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="restaurants.reserve",
                        verbose_name="Бронирование",
                    ),
                ),
            ],
            options={
                "verbose_name": "История бронирования",
                "verbose_name_plural": "История бронирований",
            },
        ),
        migrations.AddField(
            model_name="reserve",
            name="table",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tables",
                to="restaurants.table",
                verbose_name="Стол",
            ),
        ),
    ]
