# Generated by Django 4.2.2 on 2025-01-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Напишите название ресторана",
                        max_length=50,
                        verbose_name="Название",
                    ),
                ),
                (
                    "table_number",
                    models.PositiveIntegerField(verbose_name="Номер стола"),
                ),
                (
                    "table_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Размер стола"
                    ),
                ),
                (
                    "start_reserve",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Начало бронирования"
                    ),
                ),
                (
                    "end_reserve",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Окончание бронирования"
                    ),
                ),
            ],
            options={
                "verbose_name": "Резерв",
                "verbose_name_plural": "Резервы",
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Напишите название ресторана",
                        max_length=50,
                        verbose_name="Название",
                    ),
                ),
                (
                    "total_seats",
                    models.PositiveIntegerField(verbose_name="Общее количество мест"),
                ),
                (
                    "free_seats",
                    models.PositiveIntegerField(
                        verbose_name="Количество свободных мест"
                    ),
                ),
                (
                    "reserved_seats",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество занятых мест"
                    ),
                ),
                (
                    "table_number",
                    models.PositiveIntegerField(verbose_name="Номер стола"),
                ),
                (
                    "table_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Количество мест за столом",
                        null=True,
                        verbose_name="Размер стола",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
            },
        ),
    ]
