# Generated by Django 4.2.2 on 2025-01-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="client",
            new_name="user",
        ),
    ]
